---
abstract: 'Log Information When `perl` Runs'
author:
  - 'Ingy döt Net <ingy@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.029, CPAN::Meta::Converter version 2.143240'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Devel-PerlLog
no_index:
  directory:
    - inc
    - t
    - xt
    - example
requires:
  YAML::XS: '0.55'
  perl: v5.8.1
resources:
  bugtracker: https://github.com/ingydotnet/devel-perllog-pm/issues
  homepage: https://github.com/ingydotnet/devel-perllog-pm
  repository: https://github.com/ingydotnet/devel-perllog-pm.git
version: '0.04'
